### ISSUE TITLE
IndexError:

### ISSUE THREAD

**Issue by tanjia123456** [benedekrozemberczki/NGCN#10]
hello, when I run main.py, the error message occurs:

File "D:\anaconda3.4\lib\site-packages\torch_sparse\spmm.py", line 30, in spmm
    out = matrix[col]
IndexError: index 10241 is out of bounds for dimension 0 with size 10241

the content of the spmm.py:
`# import torch
from torch_scatter import scatter_add

def spmm(index, value, m, n, matrix):
    """Matrix product of sparse matrix with dense matrix.
    稀疏矩阵与稠密矩阵的矩阵乘积

    Args:
        index (:class:`LongTensor`): The index tensor of sparse matrix.
        value (:class:`Tensor`): The value tensor of sparse matrix.
        m (int): The first dimension of corresponding dense matrix.
        n (int): The second dimension of corresponding dense matrix.
        matrix (:class:`Tensor`): The dense matrix.
      :rtype: :class:`Tensor`
    """

    assert n == matrix.size(0)

    row, col = index
    
    matrix = matrix if matrix.dim() > 1 else matrix.unsqueeze(-1)

    out = matrix[col]
    out = out * value.unsqueeze(-1)
    out = scatter_add(out, row, dim=0, dim_size=m)

    return out
`
by the way, I use my own datasets, and the number of node is 10242. do you know how to solve it?

**Comment by benedekrozemberczki** [comment]
You should reshape your edges.

**Comment by benedekrozemberczki** [comment]
Could you star the repo and follow me on github?
