### ISSUE TITLE
Citeseer and Pubmed Datasets

### ISSUE THREAD

**Issue by bousejin** [benedekrozemberczki/NGCN#3]
Hi Benedek,

Thank you so much for the code. I want to run your code on Citeseer and Pubmed datasets. Would you mind providing Citeseer and Pubmed data in this format? By the way, after running MixHop model with default parameters I got the test accuracy 0.7867. Did the accuracy depend on the system that the code is running?

Thanks in advance

**Comment by benedekrozemberczki** [comment]
Should not.

**Comment by bousejin** [comment]
Thank you. And, what about the datasets? Can I have it?

**Comment by benedekrozemberczki** [comment]
PyTorch Geometric has those built in.
