### ISSUE TITLE
Is this an official implementation?

### ISSUE THREAD

**Issue by dragen1860** [benedekrozemberczki/NGCN#4]
thanks for your well documented repo.
Is this official implementation?

**Comment by benedekrozemberczki** [comment]
No, this is me hacking. The NGCN layer matches the original papers performance. The MixHop version does not include retraining yet.

**Comment by CODE-SUBMIT** [comment]
> No, this is me hacking. The NGCN layer matches the original papers performance. The MixHop version does not include retraining yet.

I ran the MixHop but did not reproduce the results, may i get tips how to reproduce the results in the MixHop paper.
