### ISSUE TITLE
Higher Powers Implementation

### ISSUE THREAD

**Issue by datavistics** [benedekrozemberczki/NGCN#5]
![image](https://user-images.githubusercontent.com/22736772/62040254-49422700-b20a-11e9-819f-6722ca08e822.png)

https://github.com/benedekrozemberczki/MixHop-and-N-GCN/blob/6e4ae00055fc1aecd972081ef9c152b0e9de37c1/src/layers.py#L54-L56

To me it looks like this is implementing 
H(l+1) = σ(A^j * H(l) * W(l))

![image](https://user-images.githubusercontent.com/22736772/62041126-05e8b800-b20c-11e9-938b-bbe1d39c7d63.png)

Can you explain where W_j and the concatenation are taking place?

**Comment by benedekrozemberczki** [comment]
In the respective setup_layer_structures method in the trainer_and_networks.py file.
