### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './input/cora_edges.csv'

### ISSUE THREAD

**Issue by tanjia123456** [benedekrozemberczki/NGCN#7]
hello,
when i run src/main.py，the error message appears:
 File "pandas\_libs\parsers.pyx", line 361, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 653, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: './input/cora_edges.csv'

do you know how to solve it?

**Comment by benedekrozemberczki** [comment]
You should use linux and and the appropriate folder structure.

**Comment by tanjia123456** [comment]
must use linux?

**Comment by benedekrozemberczki** [comment]
You can change the parser?

**Comment by tanjia123456** [comment]
ok, fine. thank you
