### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by tanjia123456** [benedekrozemberczki/NGCN#9]
hello, when I run main.py, the error message occurs:
File "/home/tj/anaconda3/lib/python3.6/site-packages/torch_sparse/__init__.py", line 22, in <module>
    raise OSError(e)
OSError: libcusparse.so.10.0: cannot open shared object file: No such file or directory

my python version 3.6   cuda10.0 torch1.0.1 torch-sparse0.5.1
do you know how to solve it?

**Comment by benedekrozemberczki** [comment]
Install the appropriate package versions.
